// Export all Convex services as namespaced modules to avoid naming conflicts
export * as auth from './auth'
export * as barbers from './barbers'
export * as bookings from './bookings'
export * as branches from './branches'
export * as services from './services'
export * as events from './events'
export * as notifications from './notifications'
export * as bookingNotifications from './bookingNotifications'
export * as notificationScheduler from './notificationScheduler'
export * as products from './products'
export * as ratings from './ratings'
export * as vouchers from './vouchers'
export * as transactions from './transactions'
export * as payments from './payments'
export * as payroll from './payroll'
export * as emailMarketing from './emailMarketing'
